### ISSUE TITLE
Скрыть данные для подключения к БД

### ISSUE THREAD

**Issue by Pawnhouse** [hsomrays/practice#3]
https://github.com/hsomrays/practice/blob/c0d90a4c4c07517f35281b87957cb361caac5ae7/src/main/java/org/example/Main.java#L11

https://devcolibri.com/%D0%BF%D1%80%D0%BE%D1%81%D1%82%D0%BE%D0%B9-%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%80-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81-property-%D1%84%D0%B0%D0%B9%D0%BB%D0%B0%D0%BC%D0%B8-%D0%B2-java/

**Comment by hsomrays** [comment]
исправил

**Comment by hsomrays** [comment]
исправил

**Comment by Pawnhouse** [comment]
Скрыть данные в [application.properties](https://github.com/hsomrays/practice/blob/3f3ca713753bea4e012c668760719fea9b403111/src/main/resources/application.properties).

https://medium.com/@Marou_arnault/spring-boot-hide-your-credentials-fb1ca22ae911
