### ISSUE TITLE
Неверно реализованы CRUD операции

### ISSUE THREAD

**Issue by Pawnhouse** [hsomrays/practice#4]
Create - команда в sql INSERT, а не create table

https://github.com/hsomrays/practice/blob/c0d90a4c4c07517f35281b87957cb361caac5ae7/src/main/java/org/example/DBFunctions.java#L25

Delete - команда в sql DELETE, а не drop table
https://github.com/hsomrays/practice/blob/c0d90a4c4c07517f35281b87957cb361caac5ae7/src/main/java/org/example/DBFunctions.java#L36

**Comment by hsomrays** [comment]
исправил
