### ISSUE TITLE
Везде удалить закомментированный код

### ISSUE THREAD

**Issue by Pawnhouse** [hsomrays/practice#6]
https://github.com/hsomrays/practice/blob/d1ba8754b81c6015e3ac7b61897eb81c0dd0ebc2/src/main/java/com/example/practicespring/mapper/RecordingStudioMapper.java#L36-L43

**Comment by hsomrays** [comment]
удалил

https://github.com/hsomrays/practice/commit/3c5246a468e3bef674da30f8f8a65a4066ac5bd7
