### ISSUE TITLE
В методе контроллера принимается и передается сущность

### ISSUE THREAD

**Issue by Pawnhouse** [hsomrays/practice#7]
https://github.com/hsomrays/practice/blob/d1ba8754b81c6015e3ac7b61897eb81c0dd0ebc2/src/main/java/com/example/practicespring/controllers/ArtistController.java#L27

Если есть ArtistDto, то его нужно отправлять и принимать в методах контроллера

**Comment by hsomrays** [comment]
исправил

https://github.com/hsomrays/practice/commit/3c5246a468e3bef674da30f8f8a65a4066ac5bd7
