### ISSUE TITLE
Добавить URL бэкенда в переменную окружения

### ISSUE THREAD

**Issue by Pawnhouse** [hsomrays/practice#8]
https://github.com/hsomrays/practice/blob/39fff38064903f784a039b8546a3873b8882b126/src/app/services/artist.service.ts#L11

`"http://localhost:8080/api"`

https://habr.com/ru/articles/477214/

**Comment by hsomrays** [comment]
добавил

https://github.com/hsomrays/practice/commit/aad476ee2189a90f2b654ba987971cc0c693f2d6#diff-d897f7d114ca657c43905bff9a6ee17e53e2d1ccc172b7c258a54183653a691a
